### ISSUE TITLE
SetVolume or setPlaybackQuali don't work

### ISSUE THREAD

**Issue by TMXJojo** [rinov/YoutubeKit#10]
Hey @rinov ,
First: Thanks for this nice Library!

I tried setting the Quality and the Volume, but both function didn't work.

```swift
player = YTSwiftyPlayer( frame: youTubeView.frame, playerVars: [.videoID(videoID), .autoplay(true), .registerStartTimeAt(Int(currentTime)) ,             
                .showInfo(true), .showRelatedVideo(false)])  
 // Set player view      
 ...      
 // Set delegate for detect callback information from the player
 player.delegate = self     
 player.setPlaybackQuality(getQuality())    
 player.setVolume(50)

```

**Comment by ctwdtw** [comment]
@TMXJojo :
I tried to tackle the problem and here is what I found:
1. I think we need to load the player before we can send any command to the player, otherwise we will get an error like this: `Error Domain=WKErrorDomain Code=4 "A JavaScript exception occurred" UserInfo={WKJavaScriptExceptionLineNumber=1, WKJavaScriptExceptionMessage=ReferenceError: Can't find variable: player, WKJavaScriptExceptionColumnNumber=7, WKJavaScriptExceptionSourceURL=about:blank, NSLocalizedDescription=A JavaScript exception occurred}` 
2. Even I did load the `player`, before I  call the `setVolume(_:)` method, I still get another error like this:  `Error Domain=WKErrorDomain Code=5 "JavaScript execution returned a result of an unsupported type" UserInfo={NSLocalizedDescription=JavaScript execution returned a result of an unsupported type}` from line 273 of `YTSwiftyPlayer.swift`.

I did not see a volume adjustment bar in the HTML5 player (I can only mute or unmute the player through my mouse) therefore I tried `player.mute()` and `player.unMute()`, same error message happened.

I then add two functions to the `player.html`:

```
function mute() {
      player.mute()
}
    
function unMute() {
      player.unMute()
}
```  
and use `evaluateJavaScript(_ :completionHandler:)` to test it, then the `error` and `result` in the completionHandler is both nil, and the HTML player response correctly!

Therefore, we may need to do the same thing for `setVolume(_:)` and `setPlaybackQuality(_:)`

I do not know the reason why, but this is what I found, hope this will give you some hint @TMXJojo .

**Comment by TMXJojo** [comment]
@ctwdtw  Thanks for your reply!

You are right, with saying we have to wait until the player is loaded. I set `player.mute()`  in `playerReady(_ player: YTSwiftyPlayer) ` and it works! 

Unfortunately `setPlaybackQuality` not...

I hope there will be a solution soon. :)

**Comment by rinov** [comment]
I'm sorry, YoutubeKit is currently support almost all YoutubeIFrameAPI, but some of function is disabled on iOS due to following reasons.

- Video volume depends on the device's own setting rather than the player on mobile device
- Playback quality depends on view size and network condition in mobile environment

I decide that providing `setVolume` produce misleading,  so i'd like to delete `volume` related function from this library.

**Comment by rinov** [comment]
https://github.com/rinov/YoutubeKit/releases/tag/0.2.2
