### ISSUE TITLE
Videos only plays audio

### ISSUE THREAD

**Issue by abouzoubaa** [rinov/YoutubeKit#28]
I am having a very bizarre issue where the video plays only audio but does not show:
Here is the code:

import AppKit
import CocoaYoutubeKit
import WebKit

class PlayViewController: NSViewController {

    private var player: YTSwiftyPlayer!
    
    override func viewDidAppear() {
        super.viewDidAppear()
        self.view.window?.title = "Videos"        
        self.view.window?.titleVisibility = .hidden
        self.view.window?.titlebarAppearsTransparent = true
        self.view.window?.styleMask.insert(.fullSizeContentView)       
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()

        player = YTSwiftyPlayer(
            frame: CGRect(x: 0, y: 0, width: 640, height: 480),
            playerVars: [.playsInline(true), .videoID("61-AN084GH0"), .loopVideo(true), .showRelatedVideo(false), .showModestbranding(true), .showInfo(false), VideoEmbedParameter.showControls(VideoControlAppearance.hidden)])
        
        player.autoplay = true        
        view.addSubview(player)
        player.delegate = self as YTSwiftyPlayerDelegate
        
        player.loadPlayer()
       }
}

Video shows only if I replace "view.addSubview(player)" with "view = player"
For info the class PlayViewController is a SplitViewItem Controller.
When I don't use a SplitViewController with 2 child controllers and use only a regular ViewController this problem disappears.

Thank you for helping.

**Comment by rinov** [comment]
This issue seems to be related to the frame of the YTSwiftyPlayer when it's added to the view hierarchy of the PlayViewController. When you replace the view of the PlayViewController with the player, the player takes the frame of the view, which is why the video is displayed correctly.

However, when you add the player as a subview of the view, it seems that its frame is not being set correctly, which could be why the video is not being displayed.

To fix this issue, you could try setting the frame of the player to match the bounds of the view after adding it as a subview. Here's how you could modify your code like this:

```swift
view.addSubview(player)
player.frame = view.bounds
player.autoresizingMask = [.width, .height]
```
