### ISSUE TITLE
Youtube Player with camera recording 

### ISSUE THREAD

**Issue by Saqibali73** [rinov/YoutubeKit#31]
I am trying to play a youtube with in my application and same time trying to record user using front camera.

Issue i am facing is youtube video go paused when video recording starts.

**Comment by rinov** [comment]
The issue you're facing is likely due to the fact that both the YouTube player and the camera are trying to access the audio session concurrently. In iOS, only one audio session can be active at a time. When you start recording with the camera, it likely activates its own audio session, which then interrupts the YouTube player's audio session, causing the video to pause.

To resolve this issue, you can try setting the audio session category to AVAudioSession.Category.playAndRecord before playing the video.
