### ISSUE TITLE
Video zooms in and shows Quick Time Player logo(?) when you forward the progress bar to the end

### ISSUE THREAD

**Issue by MarinRados** [rinov/YoutubeKit#41]
Happens every time, see attachment.

![simulator screen shot - iphone xs max - 2018-12-13 at 15 04 48](https://user-images.githubusercontent.com/15719349/49943621-ae017900-fee8-11e8-827c-3d971c81b6f5.png)

**Comment by rinov** [comment]
This issue might be related to the default behavior of the YouTube video player when it reaches the end of a video. (Normally, when a video ends, the YouTube player displays thumbnails of related videos, which is consistent with the behavior of YouTube's web player)

However, as you've described, when you advance the progress bar to the end of the video, the video zooms in and displays what appears to be the Quick Time Player logo. This is due to YouTubeKit utilizing the YouTube Web Player API, and thus its behavior depends on that API.
