### ISSUE TITLE
YTSwiftyPlayerDelegate not working?

### ISSUE THREAD

**Issue by hangocanh2303** [rinov/YoutubeKit#8]
in example project, YTSwiftyPlayerDelegate never called?

**Comment by ctwdtw** [comment]
face the same problem, here is my environment:
Xcode 10.0 beta 2 (10L177m)
run on Simulator iPhone 6S Plus 9.2

**Comment by ctwdtw** [comment]
I think I found the reason why the delegate never called:
```
public init(frame: CGRect = .zero, playerVars: [VideoEmbedParameter] = []) {
    let config = WKWebViewConfiguration()
    //set some values for config ...
    super.init(frame: frame, configuration: config)
    //set userContentController 
    config.userContentController = userContentController
}
```
The userContentController was set after super.init(frame:configuration:) and that's why 
`userContentController(_ :didReceive: )` never got called hence functions in  `YTSwiftyPlayerDelegate `protocol never got called. See these gist for further elaborate:

[userContentControllerDebug.swift](https://gist.github.com/ctwdtw/1306a09386c8debd4bd49af7f4f108b4)
[JSforUserContentControllerDebug.html](https://gist.github.com/ctwdtw/abb285949d7fc7769ed097e304c66c14)

I am not sure if this is a bug of Apple or there is a simple elegant way to fix it...However, I really learned a lot by reading through @rinov 's source code. Thank you for this library :)

**Comment by ctwdtw** [comment]
WKWebView's configuration property is of  `@NSCopying`, after reading Apple's documents, I found that one can not change the configuration property after initialization and expect WKWebView behave differently, therefore we need to change the way we implement the initialization of `YTSwiftyPlayer`:
[WKWebViewConfiguration document](https://developer.apple.com/documentation/webkit/wkwebviewconfiguration)

Quote:
> WKWebViewConfiguration is only used when a web view is first initialized. You cannot use this class to change the web view's configuration after it has been created.

**Comment by hangocanh2303** [comment]
@rinov a lot of video can't play if not set base url in loadPlayer method. 
loadHTMLString(html, baseURL:  URL(string: "https://www.youtube.com/"))
